### ISSUE TITLE
Add button difficult to see

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#121]
Users are reporting difficult in seeing the Add text. Could we add some type of background to this or perhaps turn it into a button? If we do, then we need to be consistent with all the words (Edit, Filter, etc). 

@mtedeschi what are your thoughts?

**Comment by jwalgran** [comment]
The standard style of iOS 7 and later apps is to have plain text, borderless buttons. Users have had several years to adjust to this style, so I am going to close this.
