### ISSUE TITLE
Display species after selecting it in edit page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#125]
When you click Set Species and choose a species name, it would be nice if the species name would remain visible instead of returning to the “Set Species >” text. It makes it look like it didn’t capture your entry.

**Comment by jmorrison1847** [comment]
Recently noticed by a user.

**Comment by jwalgran** [comment]
Fixed by https://github.com/OpenTreeMap/otm-ios/pull/303
