### ISSUE TITLE
iOS attempts to autocorrect usernames

### ISSUE THREAD

**Issue by lliss** [OpenTreeMap/otm-ios#155]
There is likely a way to inform the OS not to autocorrect certain types of fields and this should be done on the username field as that is likely to annoy users.

**Comment by jwalgran** [comment]
Correction is set to "No" in the current storyboard

<img width="786" alt="screen shot 2016-09-15 at 2 28 17 pm" src="https://cloud.githubusercontent.com/assets/17363/18568179/be488060-7b50-11e6-9c98-2e0a65ee3e1c.png">
