### ISSUE TITLE
Add tree number to tree detail page on app

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#208]
Users have reported that it would be useful to show the tree number so that it is easier to reference a particular tree.

**Comment by jwalgran** [comment]
The tree number is shown on the detail page

<img width="707" alt="screen shot 2017-01-26 at 1 20 24 pm" src="https://cloud.githubusercontent.com/assets/17363/22348892/9357ab46-e3ca-11e6-9194-9ad6c0dac9b3.png">
