### ISSUE TITLE
On Switch Tree Maps, should have loading indicator for "My Tree Maps"

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-ios#214]
Sometimes My Tree Maps takes several seconds to load from the server. During this time the only thing visible on screen is "search all tree maps", and it's easy to think that this is the only option. Some kind of loading or other indicator should be added so a user will know that "My tree maps" is coming, it's just not downloaded yet

**Comment by jwalgran** [comment]
This page now has a spinner.
