### ISSUE TITLE
Can't edit existing tree

### ISSUE THREAD

**Issue by caseypt** [OpenTreeMap/otm-ios#218]
I tried several times this weekend and this morning to enter details (photo, species, diameter) for this [tree](https://www.opentreemap.org/phillytreemap/features/343742/). Each time, upon saving my changes, I get this message:

"Sorry. There was a problem saving the updated tree details."

If this is a permissions problem, consider showing this in the message or hiding the edit link.

**Comment by RickMohr** [comment]
This has been fixed.

**Comment by caseypt** [comment]
Alright!
