### ISSUE TITLE
App crashes when using camera to add a picture

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#238]
Reported bug: app crashes when adding a photo using the camera (6s+) but does not crash when adding a photo from an existing album. Currently not replicated (so far tested on a 6+).

**Comment by jmorrison1847** [comment]
Could be related to #78

**Comment by jwalgran** [comment]
Clearing the date-based milestone because we have switched to release number milestones

**Comment by jwalgran** [comment]
Closing as duplicate of #78
