### ISSUE TITLE
Private instances are inaccessible

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#241]
I can't seem to load private instances that I'm a member of when I search for available tree maps in the iOS app—this could be related to the feedback we got from Mike yesterday.

**Comment by jwalgran** [comment]
Do you know if the instances are accessible from the Android application?

Can you please outline the specific steps you are going through to get to the instance list (probably a short list)

**Comment by jmorrison1847** [comment]
I checked using one of the in-house Android phones and all of my maps displayed, even the private one. The steps are:

1. Load up the app, log in. 
2. Search all tree maps
3. Only public maps display
4. Set one of my private maps to public temporarily
5. Repeat steps 1 and 2
6. Formerly private map that is now public shows up in the list

**Comment by jwalgran** [comment]
I was unable to reproduce this issue. I think the source of confusion is the poorly labeled "Search All Tree Maps" button. The Android app more correctly labels this button "See All Public Tree Maps".

**Comment by jmorrison1847** [comment]
I'm still having trouble with this issue. I personally believe this is what prevents clients from accessing their maps on the mobile apps while in trial mode (at least on iOS—I have not tested this on Android). "Pics or it didn't happen." Here's the process to recreate this experience:

Step 1: I created a map (https://www.opentreemap.org/mobileapptrialtest/)
Step 2: While in trial mode, I pulled up the iOS App and logged in—it did not appear in the list of maps either on this page:
![img_5057](https://cloud.githubusercontent.com/assets/12401491/11691979/6dd5789e-9e6b-11e5-8eee-65e28d19ffe8.jpg)
or this page:
![img_5058](https://cloud.githubusercontent.com/assets/12401491/11691993/7edfc342-9e6b-11e5-8367-a59d53b783ef.jpg)
Step 3: closing, restarting, and re-logging in did not make it appear, even over a 5-minute span of trying various combinations of those actions.
Step 4: In the super admin page, I took the instance out of trial mode and eliminated the expiration date (in order to avoid the red bars of death).
Step 5: Repeating steps 2 and 3 did not make the map appear—it was still private, so that had not changed.
Step 6: I made the map public:
![screen shot 2015-12-09 at 11 47 02 am](https://cloud.githubusercontent.com/assets/12401491/11691923/28863814-9e6b-11e5-9827-7867461b8a57.png)
Step 7: I restarted the app and logged in again and the map immediately appears in the "Search All Tree Maps List" (See the entry for "Mobile Apps Tester")
![img_5059](https://cloud.githubusercontent.com/assets/12401491/11692008/942e941c-9e6b-11e5-9bbe-e6bcc2ee8bd1.jpg)
Step 8: I made the map private again.
Step 9: I restarted the app and logged in again and the map was no longer accessible:
![img_5060](https://cloud.githubusercontent.com/assets/12401491/11692021/a500ecfe-9e6b-11e5-963e-906092676819.jpg)

**Comment by jmorrison1847** [comment]
A secondary (potentially primary) issue is that for some reason I have never been able to get "My Tree Maps" to appear as a list in my app—I never even knew that UI existed.

**Comment by jmorrison1847** [comment]
Reporting the aforementioned behavior as a separate issue.

**Comment by jwalgran** [comment]
https://github.com/OpenTreeMap/otm-ios/pull/244 clarifies that the button shows a list of public instances.
