### ISSUE TITLE
Load "My Tree Maps" regardless of location call

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#247]
The workflow for users having GPS problems can be problematic on the native apps when it interferes with the app's ability to load "My Tree Maps". There's a case to be made for that list loading whether or not the user opts into allowing the app to use their current location. Especially for multi-map users (e.g. a statewide network of maps), they may want to be able to view private maps that are technically a great distance from them. It might also cut down on support related questions as there are fewer variables that could prevent a new map owner (especially a trial map owner just using the software for the first time) from finding their instance.

**Comment by maurizi** [comment]
We "fixed" this in the Android app by sending a  location of 0,0 if GPS is off (https://github.com/OpenTreeMap/otm-android/pull/135).

It would be nice to fix this in a more robust fashion by adding support to the API for retrieving instances without specifying a location.

**Comment by RickMohr** [comment]
For the present work do we want to update the API, or implement a workaround like we did for Android?

**Comment by maurizi** [comment]
The major problem with the android workaround is that maps are sorted by distance to [null island](https://en.wikipedia.org/wiki/Null_Island), which is very helpful.

Updating the API could allow for a more useful sort order, like alphabetical.

**Comment by jwalgran** [comment]
The root issue is that the iOS app does not make an API request until the users location is found to a specific level of accuracy, or the time out (currently set in Implementation.plist to 15 seconds) expires. The long timeout makes things look broken.

I agree that the API [should be improved](https://github.com/OpenTreeMap/otm-core/issues/1480), but we need to fix this behavior from the iOS app regardless, so I would recommend going ahead with the 0,0 trick for now.

**Comment by RickMohr** [comment]
Looks to me like we're already doing the (0,0) trick.
https://github.com/OpenTreeMap/otm-ios/blob/master/OpenTreeMap/src/OTM/Controllers/OTMInstanceSelectTableViewController.m#L94
