### ISSUE TITLE
Add species to the info for recent edits on the profile page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#25]
The profile page includes links to recent edits and newly added trees. While each entry in the list goes to the tree's detail page, it would be useful to include the tree's species on the list on the profile page so users can skim the list for particular trees more easily.

**Comment by jwalgran** [comment]
Recent edits were disabled in https://github.com/OpenTreeMap/otm-ios/commit/fd436d88ca387296ddd4525c163823f7672d609c
