### ISSUE TITLE
Current filter page design has overlapping controls

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-ios#268]
Support for custom mobile search fields will be deployed soon. The filter screen is not designed for long field names.

<img width="322" alt="screen shot 2016-01-27 at 11 50 23 pm" src="https://cloud.githubusercontent.com/assets/17363/12637253/0aa93820-c551-11e5-8ae5-feecaa6c05be.png">

**Comment by dboyer** [comment]
@designmatty We could use some design help on this.

**Comment by designmatty** [comment]
I would recommend setting a max width on the label to force the label to go to the next line. Then vertically centering the label and the inputs. In the attached example (spotify app) the label descriptions fall to two lines. 
![6033_f](https://cloud.githubusercontent.com/assets/1928955/12677520/a02ed3de-c667-11e5-8607-449f23dfb10d.jpg)
