### ISSUE TITLE
When adding a tree, species incorrectly says "(not set)"

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-ios#281]
1) Start adding a tree. Species field says "(not set)"
2) Choose a species. Species field still says "(not set)"

**Comment by dboyer** [comment]
I saw this several times when demoing the iOS app. It confused quite a few people and caused them to think the app either wasn't functioning or that the species hadn't saved.

**Comment by hadleystein1** [comment]
+1 PA DCNR
