### ISSUE TITLE
"Cannot connect to server" Error Message

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#287]
Dale Carlon received  "There was a problem connecting to server. Press OK to try again." error message mid-mapping in the field. Tried to exit and re-open the application, but received same error. Once he deleted the app and re-downloaded, the issue went away.  I suspect this is due to the fact that the app was not updated in the App Store, and that he could have simply updated the app.

Meadowood Manor Map: https://www.opentreemap.org/meadowoodmanor

![img_0353 1](https://cloud.githubusercontent.com/assets/15219245/13829539/e4986016-eb9d-11e5-9698-ea21525c4bb4.PNG)

**Comment by RickMohr** [comment]
@jwalgran, any ideas on what to do with this? I have an old version of the app installed on my iPhone and it comes up fine. Not sure how to reproduce, or how to proceed otherwise.

**Comment by jwalgran** [comment]
The screen shot shows the error dialog being shown over the splash page. This is the line that should be showing dialog:

https://github.com/OpenTreeMap/otm-ios/blob/master/OpenTreeMap/src/OTM/Controllers/OTMSplashViewController.m#L46

The app tries to automatically switch to the instance previously saved to the app preferences

https://github.com/OpenTreeMap/otm-ios/blob/master/OpenTreeMap/src/OTM/Controllers/OTMSplashViewController.m#L80

If that instance goes dormant, private, or is in some other way inaccessible, we will run into the situation described.

A simple solution of this would be to manually log the failure to Rollbar, then proceed to show the instance select page.

```objectivec
[self afterSplashDelaySegueTo:@"selectInstance"]
```

**Comment by RickMohr** [comment]
You're suggesting that we remove the code that shows the dialog, and instead call rollbar and show the instance select page, right?

**Comment by jwalgran** [comment]
Right. If we fail to load the instance specified in the preferences (maybe because it is no longer accessible) it is reasonable to log the failure and proceed to showing the instance selector.

**Comment by maurizi** [comment]
Do we need to have a special error case for a skinned app? If say, LA turns
their map private for some reason? We don't want to show the instance
switcher on the LA app.

On Tue, Apr 5, 2016, 15:03 Justin Walgran <notifications@github.com> wrote:

> Right. If we fail to load the instance specified in the preferences (maybe
> because it is no longer accessible) it is reasonable to log the failure and
> proceed to showing the instance selector.
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeMap/otm-ios/issues/287#issuecomment-205949850>
>
-- 

Michael Maurizi, Software Developer
Azavea |  990 Spring Garden, 5th Floor, Philadelphia, PA
mmaurizi@azavea.com <rcr@azavea.com> | Web azavea.com
<http://www.azavea.com/>  |  @azavea <http://twitter.com/azavea>

**Comment by RickMohr** [comment]
Good point. If the app doesn't allow switching instances (e.g. LA) we should keep the current behavior.
