### ISSUE TITLE
The implementation specific image assets and config files required to build the application are not included

### ISSUE THREAD

**Issue by conantp** [OpenTreeMap/otm-ios#294]
Hi, reading the docs, I see the link for the otm-legacy-ios skin, which is out of date. 

So I installed a default skin using fabric, but on building I get a bunch of messages about missing assets, like:

error: /otm-ios/OpenTreeMap/SpotlightIcon@2x.png: No such file or directory

I've worked through some of the missing assets, but there's a lot of them. Is there a way I can get a build-able skin to work off of?

**Comment by jwalgran** [comment]
The core team will be documenting all the implementation specific images and config files required by v2.x of the iOS application. I am updating the title of this issue to reflect the root problem.

**Comment by jwalgran** [comment]
I had previously compiled this list on 5/2/2015. It is deficient in a couple ways:
- It does not explain how big the images should be and what UI element they correspond to
- It does not include the plists


In-app artwork:
Chevron_left.png
Chevron_left@2x.png
Chevron_right.png
Chevron_right@2x.png
Default_feature-image.png
Default_feature-image@2x.png
Profile_favorited.png
Profile_favorited@2x.png
Profile_unfavorited.png
Profile_unfavorited@2x.png
TabBar_about-active.png
TabBar_about-active@2x.png
TabBar_about.png
TabBar_about@2x.png
TabBar_details-active.png
TabBar_details-active@2x.png
TabBar_details.png
TabBar_details@2x.png
TabBar_profile-active.png
TabBar_profile-active@2x.png
TabBar_profile.png
TabBar_profile@2x.png
TabBar_treemap-active.png
TabBar_treemap-active@2x.png
TabBar_treemap.png
TabBar_treemap@2x.png
Treemap_Contactbook.png
Treemap_Contactbook@2x.png
gps_icon.png
gps_icon@2x.png
gps_icon_14.png
gps_icon_14@2x.png
handle_icon.png
handle_icon@2x.png
location_marker.png
location_marker@2x.png
profile.png
profile@2x.png
selected_marker.png
selected_marker@2x.png
selected_marker_small.png
selected_marker_small@2x.png   

About page content:
about.html

Standard iOS launch images:
Default-568h@2x.png
Default@2x.png
Default.png      

Standard iOS icons:
Icon.png
Icon@2x.png
SettingsIcon.png
SettingsIcon@2x.png
SpotlightIcon.png
SpotlightIcon@2x.png
iTunesArtwork.png
iTunesArtwork@2x.png
icon-72.png
icon-72@2x.png
