### ISSUE TITLE
Production errors are logged as development in Rollbar

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-ios#295]
Need to set the proper environment name.

**Comment by RickMohr** [comment]
I propose something like
```objective-c
    RollbarConfiguration *config = [RollbarConfiguration configuration];
#if TARGET_IPHONE_SIMULATOR
    config.environment = @"development";
#else
    config.environment = @"production";
#endif
    [Rollbar initWithAccessToken:@"POST_CLIENT_ITEM_ACCESS_TOKEN" configuration:config];
```

**Comment by jwalgran** [comment]
The downside to that implementation is that dev or staging builds running on an actual device will generate `production` messages in Rollbar.

An alternate implementation would be to template the value into `Implementation.plist`, similar to how the Android skinning process writes an `environment` key into `defaults.xml`, and exactly how we set other environment specific values like server endpoint URLs.
