### ISSUE TITLE
If user lacks edit permission for `plot.geom`, UI allows tree creation steps but final step fails

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-ios#296]
Rollbar shows that the `plot_id` argument to `update_or_create_plot ` is `None` but the `request.body` contains `plot: {}`.

API version: 4 (for all 10 occurrences)
Instance: greenprintmaps (Sacramento)
User: hesmith5@uwalumni.com

View details in Rollbar: [https://rollbar.com/Azavea/OpenTreeMap/items/1004/](https://rollbar.com/Azavea/OpenTreeMap/items/1004/)

**Comment by RickMohr** [comment]
@jwalgran, rollbar shows these headers:
`request.headers.User-Agent`:	`OpenTreeMap 2.3.0 (iPhone; iPhone OS 9.2.1; en_US)`
`request.headers.Applicationversion`:	`ios-(null)-b(null)`

I don't think either of those tells us the app version, but perhaps we could get it to.

`OpenTreeMap 2.3.0` is strange since this happened yesterday and 2.4.0 is in production.

**Comment by jwalgran** [comment]
We have confusing set of version numbers right now. 2.3.0 is the latest iOS app version.

The `ios-(null)-b(null)` issue is logged. https://github.com/OpenTreeMap/otm-ios/issues/290
