### ISSUE TITLE
Cannot add Empty Planting Site from iOS application

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#304]
On the web "Add a Tree" workflow, not entering information and clicking "Next" automatically generates an Empty Planting Site. You cannot add an Empty Planting Site from the iOS application. Clicking "Add a Tree" and not entering information generates a tree with missing species data. There does not appear to be any way to add an Empty Planting Site on iOS.

![screen shot 2016-06-10 at 12 23 28 pm](https://cloud.githubusercontent.com/assets/15219245/15971241/2fc76176-2f06-11e6-92e1-d1ea0e9a7185.png)

![screen shot 2016-06-10 at 12 23 34 pm](https://cloud.githubusercontent.com/assets/15219245/15971243/31537188-2f06-11e6-8cf4-ab2644f195ab.png)

![screen shot 2016-06-10 at 12 23 13 pm](https://cloud.githubusercontent.com/assets/15219245/15971239/2e5e29fa-2f06-11e6-8066-782dfe815601.png)

**Comment by jwalgran** [comment]
An example of what is logged when adding a map feature but not specifying any tree fields
```
2016-06-10 09:37:50.076 OpenTreeMap[81184:19805995] Sending new tree data:
{
    plot =     {
        "address_city" = Vernon;
        "address_street" = "2700 Fruitland Ave";
        "address_zip" = 90058;
        geom =         {
            srid = 4326;
            x = "-118.2224679709522";
            y = "33.99403798166913";
        };
    };
    tree =     {
    };
}
```

We could remove the empty `tree` from the POST data to avoid this, but that is only a partial solution. Logging that a tree is present but not having any species or diameter information is different then logging an empty pit. The web app accomodates this distinction.

Question: Do we only allow creating trees that have at least one field filled in, or do we implement the "Add Tree" button that exists in the web app?

**Comment by hadleystein1** [comment]
+1 because this was reported by a customer.

**Comment by RickMohr** [comment]
@hadleystein1, note you can add the "customer" GitHub label, very helpful for prioritizing.

**Comment by dboyer** [comment]
This may be a reason to move toward the tree present yes/no field we haven't implemented.

**Comment by jwalgran** [comment]
We are going to start by making the iOS app work like the Android app. If you do not specify any tree field values, a tree is not created.

**Comment by RickMohr** [comment]
The iOS app does correctly add an empty planting site if you provide no tree data.

The problem is that it displays the title "Missing Species" for an empty planting site.
