### ISSUE TITLE
iOS application unable to find location

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#318]
Treefolks (customer in Austin, TX) reported that iOS application "hasn't been able to locate me for the last couple mapping events." The swirly, finding location symbol appears in the lower right corner of the map the entire time. 

Other notes:

- She reported that it located her just now (4:50pm) after not located her for seven hours today, and experienced no location change or cell service change within that time period. 

- Apple and Google do not have any problem locating her device immediately, when she opens the mapping applications on her phone so it does not seem to be related to cell service. 

- Treefolks has organization mapping events with younger students and has had to forgo some recent events as students are unable to locate themselves by hand.

**Comment by jwalgran** [comment]
I was able to reproduce this on my personal iPhone, which is good news for tracking down the root cause of the issue.
