### ISSUE TITLE
Add Google Analytics code

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#320]
https://developers.google.com/analytics/devguides/collection/ios/v3/

Google distributes the iOS client as a [CocoaPod](https://cocoapods.org/).

There is an old, open PR (#53) that may serve as a starting point for implementing CocoaPods.

Analytics ID and other implementation specific configuration values need to be templated.

Having all view controllers inherit `GAITrackedViewController` will handle sending events whenever a view appears, but all the view controllers will need to be edited to set a "screenName".
https://developers.google.com/analytics/devguides/collection/ios/v3/reference/interface_g_a_i_tracked_view_controller

Questions:
- What should be tracked?
  - Views appearing?
  - Taps within views?
  - User ID?

**Comment by dboyer** [comment]
@kjjustice - Thoughts on what should be tracked in the iOS app?

**Comment by kjjustice** [comment]
In both the iOS and Android app, my ideal tracking would be:

- Location Search (do not care about capturing the location they searched for, just the count of location searches)
- Filter Searches (if possible what filters they used: species vs diameter vs height vs missing stuff)
- "Add Tree" clicks
- "Save" on Add Tree workflow
- Add a Picture clicks (Add a Tree vs Edit Tree Details breakdown would be awesome)
- Tree Detail "Edit" clicks 
- Tree Detail "Save" clicks

My guess is that the mobile apps is will show more editing and adding Trees, so we need this information the most. People are almost certainly not going to add photos inside at their desk, so it would be good to understand if and how people are taking photos in the field. Lastly, the filter function is closely related to work order management (filter by trees assigned to me, or by trees that need trimming, etc), so it would be good to add in that code now.
