### ISSUE TITLE
iOS application will not open on phone, downloads/updates completed

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#336]
In attempt to open iOS application, I click on the OpenTreeMap icon and application attempts to open. The green screen with the OpenTreeMap logo flashes across the phone screen and then the application immediately closes. I confirmed that all updates both to the application and phone software are up to date. I also tried turning the phone off and back on again.

**Comment by jwalgran** [comment]
2.6.0 was approved by Apple and on Friday December 2nd. The problem may be related to the update.

I do no see any crashes reported in Rollbar.

Is this on one of your personal devices or an Azavea device or a customer report? If it is a device we have physical access to we can connect it to a developer machine and may be able to get logs to help diagnose the problem.

**Comment by RickMohr** [comment]
I installed 2.6.0 from the app store on my iPhone 6 running iOS 10.1.1 and it's working fine.

**Comment by hadleystein1** [comment]
This issue is on my personal phone, and was discovered as I tried to look into a customer issue last night. Is it possible it does not appear as a crash in Rollbar because the application is not opening?

**Comment by jwalgran** [comment]
Yes. Rollbar is one of the first things that is set up when the application launches, but it does look like the crash is occurring earlier in the application start-up process.

Another data point, my 4s running iOS 9.x is running the latest version too.

**Comment by dboyer** [comment]
@hadleystein1 If you uninstall and reinstall the app, do you have the same issue?

**Comment by hadleystein1** [comment]
@dboyer @jwalgran I uninstalled and reinstalled the application and it appears to now be working fine. Hmm.

**Comment by dboyer** [comment]
Are we getting other reports of this issue @hadleystein1 ? If not, let's close it.

**Comment by hadleystein1** [comment]
@dboyer No additional reports of this issue. Will close and reopen if it comes up again.
