### ISSUE TITLE
"Sorry. There was a problem saving the new tree" Error Message

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#337]
Community Greening (https://www.opentreemap.org/communitygreening/map/) reported the above error message on the iOS application when trying to add a tree. The tree added despite the warning message. 

![img_8465](https://cloud.githubusercontent.com/assets/15219245/21357891/f585f932-c6a4-11e6-9cea-7d903ac1b420.PNG)

**Comment by hadleystein1** [comment]
+1 reported by Evanston on 1/11/17. https://www.opentreemap.org/evanstondemo

**Comment by hadleystein1** [comment]
+1 reported by Trees Forever on 1/13/17. Could this be a problem specific to trial maps? @jwalgran

**Comment by hadleystein1** [comment]
Attempted to add an empty planting site and a tree on both the Evanston (https://www.opentreemap.org/evanstondemo/) and Des Moines (https://www.opentreemap.org/desmoinesdemo/) maps. I received this error message both times - and thus reproduced the issue. I suspect this may be a widespread issue.

**Comment by RickMohr** [comment]
@hadleystein1, could you please add me to those maps?

**Comment by hadleystein1** [comment]
Done. @RickMohr 

I tested a few other maps and was still running into the same problem.

**Comment by RickMohr** [comment]
This appears to be a regression caused by our recent permissions work. The server tells the app which fields the user has permission to write, and the app sends values for only those fields. Unfortunately, `plot.location` is not in the list for new treemaps because we no longer assign a permission for it. Working on a fix, and adding this issue to the `2.14.0` milestone.

**Comment by hadleystein1** [comment]
@RickMohr I believe we have only had reports of this issue on iOS. Does your comment above imply that it is an issue across both iOS and Android? I assume this relates to adding a tree location only, and that trees can be updated if they are existing trees on the map?

**Comment by RickMohr** [comment]
I (and @maurizi) think the Android app does not have this problem.

Also, it should only be a problem for treemaps created since release 2.13.0 (11/30/2016), since older treemaps still contain permissions for `plot.geom`.

And yes you should be able to update trees, even on newer treemaps.

**Comment by RickMohr** [comment]
@dboyer, do you think this issue warrants a hot fix?

**Comment by dboyer** [comment]
Yes to the hot fix.
