### ISSUE TITLE
Mobile search filters do not match filters set in app

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-ios#346]
Tested with cloud_322_dev.ipa on an iPad

1. Created new user - debtest0130
2. User created new map - testmap0130 - core plus green infrastructure module
3. Entered billing information and made map public
4. Logged into app with debtest0130 account
5. Went to testmap0130
6. Clicked Filter
7. Listed filters include tree diameter, tree height, show missing tree diameter
8. Went to management page - confirmed that user debtest0130 had administrator role and administrator role had full write access to species
9. Went to field configuration - search fields page
10. Search fields set for display included species, diameter, tree height, missing species, missing diameter, missing photos
11. Search filters actually displayed on mobile app were tree diameter, tree height, show missing tree diameter

Missing filters: species, show missing tree species, show missing photos

This appears to only happen on newly created maps. Older maps show the filters set on the management page.

**Comment by jwalgran** [comment]
I reproduced this on both the `master` and `v2.6.0` branches of the iOS application connecting to the current production OTM (2.13.0) and the current staged pre-release (2.14.0)

If I remove "Tree Diameter" from the "Mobile" tab and reload the instance in the app I see that the change is reflected in the filter list.

<img width="689" alt="screen shot 2017-01-30 at 9 53 48 am" src="https://cloud.githubusercontent.com/assets/17363/22432463/326a3e6a-e6d2-11e6-8968-6a10eb5d8480.png">

**Comment by jwalgran** [comment]
I also checked out version 2.5.0 of the iOS app and running against the currently staged 2.14.0 OTM release I see the same issue.

I checked the instance response and the "search" section does contain both species and missing photo entries

```json
"search": {
    "missing": [
        {
            "identifier": "species.id",
            "label": "Show Missing Species"
        },
        {
            "identifier": "tree.diameter",
            "label": "Show Missing Tree Diameter"
        },
        {
            "identifier": "mapFeaturePhoto.id",
            "label": "Show Missing Photos"
        }
    ],
    "standard": [
        {
            "search_type": "SPECIES",
            "identifier": "species.id",
            "label": "Species"
        },
        {
            "search_type": "RANGE",
            "identifier": "tree.height",
            "label": "Tree Height"
        }
    ]
},
```

**Comment by jwalgran** [comment]
Here is a snippet of the instance API response for my test instance note that the `identifier` in the `search` section **does not** match the key in the fields dictionary.

```json
{
    "search": {
    
        "standard": [

            {
                "search_type": "SPECIES",
                "identifier": "species.id",
                "label": "Species"
            }
        ]
    },

    "fields": {
        
        "species.species": {
            "digits": "",
            "display_name": "Species",
            "is_collection": false,
            "data_type": "string",
            "can_write": true,
            "units": "",
            "field_key": "species.species",
            "field_name": "species",
            "canonical_units_factor": 1.0,
            "choices": []
        },
}

The "fields" list for older instances contains an item with the key "species.id".
