### ISSUE TITLE
Missing image: ptm_btn_bg.png

### ISSUE THREAD

**Issue by kbornhorst** [OpenTreeMap/otm-ios#36]
The following error appeared in the Xcode output window:
Could not load the "ptm_btn_bg.png" image referenced from a nib in the bundle with identifier "<our app id>"

OpenTreeMap-iOS-master\OpenTreeMap\resources\LoginRequiredView.xib(114):
<string key="NSResourceName">ptm_btn_bg.png</string>

OpenTreeMap-iOS-master\OpenTreeMap\resources\LoginRequiredView.xib(309):
<string key="ptm_btn_bg.png">{3, 35}</string>

**Comment by jwalgran** [comment]
We now have a default skin included in the the main `otm-ios` repo.
