### ISSUE TITLE
Species doesn’t respect the field ordering

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#365]
On iOS, if you move species down the fields list order, it still appears at the top of the list.

**Comment by daveedmesh** [comment]
Hello - any update on this bug? Thanks!

**Comment by dboyer** [comment]
![image](https://user-images.githubusercontent.com/516764/55004762-2fb97600-4fb1-11e9-83ef-d3ea5a46a8f6.png)
