### ISSUE TITLE
Form data disappears on Add Tree > Tree Detail page

### ISSUE THREAD

**Issue by kbornhorst** [OpenTreeMap/otm-ios#51]
During the second step within the Add Tree process (entering tree details) we find that as you move the page down the data entered into earlier fields are emptied.

For example, you reach the Tree Detail page and the small map shows at the top. Set Species and Change Tree Picture are next, but we skip these and enter data into Tree Diameter (in) [which auto-updates the Tree Circ field]. We move focus to Tree Height and enter a number. Scroll down a bit and enter a number into Canopy Height. If you scroll down far enough so that the Tree Diameter fields is no longer shown and then scroll back up so that it reappears we find that the field is now empty and Tree Circ is back to 0.00.

A similar issue can be seen on PhillyTreeMap when you open the Powerlines option. After making a selection your Tree Diameter entry has been emptied.

**Comment by jwalgran** [comment]
PhillyTreeMap and Tampa Tree Map have both moved to OTM Cloud and the updated iOS application that does not have this issue.
