### ISSUE TITLE
Build of fresh download of repo fails due to missing Choices.plist

### ISSUE THREAD

**Issue by Noreaster76** [OpenTreeMap/otm-ios#52]
After following the `README` (I'm pretty sure to the letter), building the app fails due to the fact that `Choices.plist` is missing. I'm using XCode 5 -- not sure if that matters.

I would suggest either adding `Choices.plist` to the repo, or doing the same thing with it that was done with the `OpenTreeMap-Info.plist` -- adding a template for it and a task in the `README` for creating it via a `fab` command.

**Comment by jwalgran** [comment]
New versions of the application load choices dynamically.
